pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r 2024-2025 2025-2026 data index.html README.txt .nojekyll public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
